image: docker:stable

stages:
    - build

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

build_blog:
    stage: build
    before_script:
        - apk add --update --no-cache make
    script:
        - make build
