image: docker:stable

stages:
    - build
    - deploy

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

build_blog:
    stage: build
    before_script:
        - apk add --update --no-cache make
    script:
        - make build
    artifacts:
        untracked: true

deploy_blog:
    stage: deploy
    before_script:
        - apk add --update --no-cache tree
    dependencies:
        - build_blog
    script:
        - cp -rp blog.williamdes.eu/public public
        - tree public
    artifacts:
        paths:
            - public
    only:
        - main
