# The URL the site will be built for
base_url = "https://blog.williamdes.eu"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Williamdes's blog"

generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags", feed = true, paginate_by = 5},
    {name = "phpMyAdmin", feed = true, paginate_by = 5},
]

[extra]
# Put all your custom variables here
links = [
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false
