# Configuration file for markdown-to-pdf styling
#
# This file defines the styling and formatting options for different Markdown elements
# when converting to PDF. Each section configures a specific element type with properties
# like font size, colors, spacing, and text decorations.
#
# Common properties for all style sections:
# - size: Font size in points
# - textcolor: RGB text color values (0-255)
# - backgroundcolor: RGB background color values (0-255)
# - afterspacing: Vertical spacing before element in points
# - afterspacing: Vertical spacing after element in points
# - alignment: Text alignment (left|center|right|justify)
# - fontfamily: Font family name
# - bold: Enable bold text
# - italic: Enable italic text
# - underline: Enable underlined text
# - strikethrough: Enable strikethrough text

# Document margins in points
[margin]
top = 8.0
right = 8.0
bottom = 8.0
left = 8.0

# Level 1 heading style (# Heading)
[heading.1]
size = 14
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.8
afterspacing = 0.5
alignment = "center"
fontfamily = "helvetica"
bold = true
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Level 2 heading style (## Heading)
[heading.2]
size = 12
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.8
afterspacing = 0.5
alignment = "left"
fontfamily = "helvetica"
bold = true
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Level 3 heading style (### Heading)
[heading.3]
size = 10
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.8
afterspacing = 0.5
alignment = "left"
fontfamily = "helvetica"
bold = true
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Emphasis style (*italic* or _italic_)
[emphasis]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.0
afterspacing = 0.0
alignment = "left"
fontfamily = "helvetica"
bold = false
italic = true
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Strong emphasis style (**bold** or __bold__)
[strong_emphasis]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.0
afterspacing = 0.0
alignment = "left"
fontfamily = "helvetica"
bold = true
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Code block and inline code style (`code`)
[code]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.4
afterspacing = 0.4
alignment = "left"
fontfamily = "helvetica"
bold = false
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Block quote style (> quote)
[block_quote]
size = 8
textcolor = { r = 128, g = 128, b = 128 }
beforespacing = 0.0
afterspacing = 0.0
alignment = "left"
fontfamily = "helvetica"
bold = false
italic = true
underline = false
strikethrough = false
backgroundcolor = { r = 245, g = 245, b = 245 }

# List item style (- item or * item)
[list_item]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.0
afterspacing = 0.5
alignment = "left"
fontfamily = "helvetica"
bold = false
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Link style ([text](url))
[link]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
afterspacing = 0.0
alignment = "left"
fontfamily = "helvetica"
bold = false
italic = false
underline = true
strikethrough = false
backgroundcolor = { r = 0, g = 0, b = 0 }

# Image caption style (![alt](url))
[image]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
afterspacing = 0.0
alignment = "center"
fontfamily = "helvetica"
bold = false
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Regular paragraph text style
[text]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.5
afterspacing = 0.5
alignment = "left"
fontfamily = "helvetica"
bold = false
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }

# Horizontal rule style (---)
[horizontal_rule]
size = 8
textcolor = { r = 0, g = 0, b = 0 }
beforespacing = 0.0
afterspacing = 0.5
alignment = "left"
fontfamily = "helvetica"
bold = false
italic = false
underline = false
strikethrough = false
backgroundcolor = { r = 255, g = 255, b = 255 }
